services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/application
      - /application/.venv
    command: [ "uv", "run", "fastapi", "dev", "main.py", "--host", "0.0.0.0", "--port", "8000" ]
