name: Prepare GitHub Registry Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  packages: write

jobs:
  build-and-deploy:
    name: BnP Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/sergeykuzmich/mfa-playground:${{ github.sha[0:7] }}
